### ISSUE TITLE
Rubyファイルが削除できない

### ISSUE THREAD

**Issue by Nozu** [Nozu/Cherry_book#1]
Rubyファイルが削除できません。

**Comment by kazunari-takahashi** [comment]
![image](https://user-images.githubusercontent.com/6755549/68459609-2f70a100-0249-11ea-8e67-b5369c64d387.png)

`ruby`ディレクトリのこと？？

git submodule になってるように見える
だとしたらこれで消せない？

```
git submodule deinit -f client
git rm -f client
```

**Comment by Nozu** [comment]
上記のコマンド実行してもエラーがでてうまくいきませんでしたが、
git pull やら git stash などしているうちに消えました!
ありがとうございました。
